---
- name: Learning to download images to be used in a cloud
  hosts: futurama
  gather_facts: yes
  # become: no


  vars:
          dir: "/tmp/images"


  tasks:
          #          - name: make image dir
          #            command: mkdir ~/images
         
          - name: Create a directory if it does not exist
            file: 
                  path: "{{ dir }}"
                  state: directory
                  # mode: 

          - name: Download file from a path
            get_url:
                    url: http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-lxc.tar.gz
                    dest: "{{ dir }}"


          - name: Unarchive a file that needs to be downloaded
            unarchive:
                    src: "{{ dir }}/cirros-0.4.0-x86_64-lxc.tar.gz"
                    dest: "{{ dir }}"
                    remote_src: yes
            become: yes

            #- name: Talk to OpenStack APIs
            # hosts: localhost
            # gather_facts: no

            #  tasks:

          #Upload an image from a local file named cirros-0.3.0-x86_64-disk.img
          #        - name: 
